package com.huan.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.net_name
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String netName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.job
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.family_native_place
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String familyNativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.username
     *
     * @param username the value for user_info.username
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.net_name
     *
     * @return the value of user_info.net_name
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getNetName() {
        return netName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.net_name
     *
     * @param netName the value for user_info.net_name
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setNetName(String netName) {
        this.netName = netName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.job
     *
     * @return the value of user_info.job
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.job
     *
     * @param job the value for user_info.job
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.family_native_place
     *
     * @return the value of user_info.family_native_place
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getFamilyNativePlace() {
        return familyNativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.family_native_place
     *
     * @param familyNativePlace the value for user_info.family_native_place
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setFamilyNativePlace(String familyNativePlace) {
        this.familyNativePlace = familyNativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated Fri May 27 01:50:31 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }
}